version: '3.8'

services:
  db:
    container_name: database
    image: mysql:5
    restart: always
    environment:
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: 'local'
      MYSQL_ROOT_PASSWORD: 'local'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    container_name: cache
    image: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  my-db:
